language: python
python:
    - "3.4"
    - "3.6"
dist: trusty

cache:
  directories:
  - bincache

git:
  submodules: true

before_install:
  - sudo apt-get -qq update
  #TODO: add any ubuntu packages needed 
  - sudo apt-get install -y python3-all-dev

script:
  - make install
  - make docs

deploy:
  provider: pages
  skip_cleanup: true
  #TODO: add this token to the project on travis (ask cwright)
  github_token: $GHPAGES_TOKEN
  local_dir: docs/_build/html
  target_branch: gh-pages
  on:
    branch: master
